- .gitignore
- README.md
'-o' for directories is still bleeding edge and has some bugs in 1.12.
See issue 14295 in https://github.com/golang/go.
- Inline separate build commands for the binaries.
- Include GO111MODULE=on as it's still required.
- Include the binaries in .gitignore
fixes #9
/priority backlog
/kind documentation
/assign @chuckha
> README: modify the build step for binaries

- actuators/actuators.go
- actuators/machine.go
- cmd/capd-manager/main.go
- cmd/capdctl/main.go
- cmd/kind-test/main.go
- go.mod
- go.sum
- kind/actions/cluster_actions.go
- kind/actions/kind.go
fix the build in current master:
- update module to github.com/kubernetes-sigs/cluster-api-provider-docker
- modify github.com/chuckha/cluster-api-provider-docker imports to
github.com/kubernetes-sigs/cluster-api-provider-docker/kind/actions
run 'go mod tidy'
- rename DeleteClusterNode to DeleteNode
the existing functions don't have Cluster in the name:
DeleteControlPlane, DeleteWorker
/kind bug
/priority backlog
/assign @chuckha
> go-modules: fix build, module name and local imports

- actuators/actuators.go
- actuators/cluster.go
I moved the Cluster actuator related code from `actuators.go` to `cluster.go` under `/actuators`. This copies the pattern used for `actuators/machine.go`
> small refactor for actuator folder

- actuators/actuators.go
closes #42 
This aligns with the assumption cluster api v0.1.4 makes with regard to the name of the kubeconfigs secret.
/cc @amy
> Fix up the secret name

- README.md
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/44 changed the secret names. Updating the docs to be in sync.
Fixes #
```release-note
NONE
```
> Fix kubeconfig fetching steps in readme

- actuators/cluster.go
- actuators/machine.go
- cmd/capd-manager/main.go
- go.mod
- logger/logger.go
This PR partially addresses: https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/22
Specifically this adds loggers to the actuators. 
The pattern used here was inspired by the aws provider. Ex: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/aws/actuators/cluster/actuator.go#L41
> Add logger to actuators

- actuators/actuators.go
- actuators/cluster.go
- actuators/machine.go
- kind/actions/kind.go
* get only running ELB containers
* remove exited ELB containers with name conflict
Cluster reconciliation should reconcile deleted ELBs
Fixes #52 
```release-note
NONE
```
> Cluster reconciliation should reconcile exited ELB

- README.md
- actuators/actuators.go
- actuators/machine.go
- cmd/capd-manager/main.go
- cmd/capdctl/main.go
- kind/actions/cluster_actions.go
- kind/actions/kind.go
This PR removes the need to copy and paste RBAC and CRD definitions. Instead we download them from a provided version of CAPI.
This PR also adds many fixes to support cluster-api v0.1.4. 
This PR adds a very annoying bug that I've yet to find a good solution for regarding kubeconfig secrets and the cluster endpoint.
Fixes #32 
```release-note
Removes `capd` and `crds` command since those were only useful for setting up a management cluster
```
> All the fixes for cluster api v0.1.4

- kind/actions/cluster_actions.go
- kind/actions/kind.go
- kind/constants/constants.go
- kind/kubeadm/config.go
**What this PR does / why we need it**:We hardcode 6443 all over the place and it should be a constant
Fixes #66 
```release-note
```
> make 6443 as a constant

- .github/main.workflow
* Renames workflow
* Only pushes master image
```release-note
NONE
```
> Minor fixup for workflow

- cmd/capdctl/main.go
This PR drops support for CAPI < v0.1.6 as there was a panic in the node ref code that prevents these versions from working.
```release-note
NONE
```
/hold
holding for testing
/cc @liztio
> Update capi base image and drop support for <v0.1.6

- logger/logger.go
This PR fixes a logging panic.
```release-note
NONE
```
/assign @liztio
> Fix logging panic

- README.md
- cmd/capd-manager/main.go
- cmd/capdctl/main.go
- cmd/kind-test/main.go
- cmd/versioninfo/versioninfo.go
- hack/set-workspace-status.sh
- scripts/build-binaries.sh
Improves debug-ability of capd by printing version info of various `capd` binaries
Fixes #
```release-note
```
> Implement version info into binaries

- .github/main.workflow
- .goreleaser.yml
We cannot push from within the goreleaser docker image. It requires credentials it cannot get.
Try to push with the configured docker. This may work since docker sockets are shared. It may not work if the images don't exist on the external socket.
```release-note
NONE
```
/assign @ashish-amarnath
> Attempt to push the images after running goreleaser

- .github/main.workflow
- .goreleaser.yml
Goreleaser will tag a base image
Then docker (outside of the goreleaser container) will tag the image goreleaser made with the right tags and then push using gcloud authentication.
we might not tbh
```release-note
NONE
```
> revamp of tag and push workflow

- .github/main.workflow
- .goreleaser.yml
- Dockerfile
- hack/verify-all.sh
This PR stops building docker images with goreleaser and builds them after goreleaser using the binaries goreleaser has built.
```release-note
NONE
```
/assign @amy
> build outside of goreleaser

- .github/main.workflow
- .goreleaser.yml
- docs/release.md
This PR adds documentation for manually releasing the container images.
Enough time has been wasted gettin GitHub actions to work.
Fixes #67 
```release-note
NONE
```
/assign @detiber 
What do you think of this release process?
> Manual release of container images

- .goreleaser.yml
- Dockerfile
- README.md
- hack/verify-all.sh
- hack/verify-docker-build.sh
- scripts/build-binaries.sh
- scripts/publish-manager.sh
This PR renames capd-manager to `manager` to align with kubebuilder's expected default.
Fixes #119 
```release-note
NONE
```
> Rename capd-manager to manager

- cmd/capdctl/main.go
- kind/controlplane/create.go
Sometimes you want to just want to set up a cluster or just create the containers.
Fixes #118 
```release-note
adds two new `capdctl` commands: `kind` (which creates a new kind cluster suitable for use with capd) and `platform` (which prints the CRDs and controllers to stdout)
```
> Break `capdctl setup` into `capdctl kind` and `capdctl platform`

- cmd/capdctl/main.go
- kind/controlplane/create.go
v1a1 version of #128 
Fixes #
```release-note
adds two new `capdctl` commands: `kind` (which creates a new kind cluster suitable for use with capd) and `platform` (which prints the CRDs and controllers to stdout)
```
> [0.1] Break `capdctl setup` into `capdctl kind` and `capdctl platform`

- .gitignore
- config/samples/infrastructure_v1alpha1_dockermachine.yaml
This is a follow up to #122.
It removes invalid samples which we can add back later if they become valid and we have a test proving they are valid.
/assign @detiber
> Ignore invalid samples

- hack/update-deps.sh
Fixes errors in go vet like:
```
verifying gomodules.xyz/jsonpatch/v2@v2.0.0: checksum mismatch
downloaded: h1:lHNQverf0+Gm1TbSbVIDWVXOhZ2FpZopxRqpr2uIjs4=
go.sum:     h1:OyHbl+7IOECpPKfVK42oFr6N7+Y2dR+Jsb/IiDV3hOo=
```
This will help the tests pass for PR #148
> fixes errors seen in verify-govet

- .gitignore
- cmd/capdctl/main.go
**What this PR does / why we need it**: This PR fixes the current `capdctl` CLI, which seems to be in a broken state on the master branch. Specifically, the problem is that the CLI uses unset string pointers to store the arguments, something that is not supported in the `flag` package. 
Since there does not seem a use case that requires string pointers rather than strings, I simply refactored all string pointers to strings.
To get the binaries to build (on macos), I also needed to update one of the dependencies in the go.sum (jsonpatch) because of a dependency mismatch. 
N/A
N/A …
> Fix NPEs in capdctl

- README.md
- examples/simple-cluster.yaml
As noted in the README, and mentioned in the last community meeting, due to the Docker VM host on MacOS, the kubeconfig stored in the secrets cannot directly be used by the user.
This PR addresses this issue for now, by introducing a temporary workaround in the form of a manual step, in which the faulty server address is replaced by the correct server address.
Other changes:
- explicitly mention the version that actually works with the instructions.
- fix the invalid example definitions.
> Add a MacOS step in the getting started secton of the README

- controllers/dockercluster_controller.go
CAPI won't proceed unless the cluster's infrastructure ref is marked as ready.
```release-note
NONE
```
This should be a help to @ashish-amarnath and anyone implementing #151 in the docker-machine
/cc @ashish-amarnath @amy 
/assign @ncdc
> Set docker cluster as ready to allow CAPI to proceed

- docs/kind.md
- docs/troubleshooting.md
Documents how to create a compatible kind cluster without `capdctl`.
This is useful when creating a long-lived kind cluster to run different CAPI providers.
Thanks to @rudoi for explaining the solution in slack!
> docs: Create a compatible kind cluster, and troubleshoot an incompatible one

- .github/ISSUE_TEMPLATE/bug_report.md
Asks users to report both the capdctl and capd-manager version, and adds helpful commands to make those easy to report.
/cc @chuckha
> Add capdctl, capd-manager versions to bug report template

- cmd/capdctl/main.go
/cc @chuckha 
**What this PR does / why we need it:**
capdctl build off the `release-0.1` branch should not default to the `latest` image of capd-manager, since that may be built off the `master` branch.
> Use v0.1 image (latest image from release-0.1 branch) instead of latest image

- api/v1alpha2/dockercluster_types.go
- api/v1alpha2/dockermachine_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
Signed-off-by: Andrew Rudoi <arudoi@newrelic.com>
This PR adds the kubebuilder annotations for enabling the status endpoint. The status patches don't work without this being enabled, as far as I'm aware.
```release-note
```
> fix: enable status endpoints

- examples/simple-cluster.yaml
Signed-off-by: Dan Finneran dan@thebsdbox.co.uk
Currently the supplied example will result in an error due to `spec.versions.kublet` missing from a machine configuration.
As shown below:
```
$ kubectl apply -f ./examples/simple-cluster.yaml
cluster.cluster.k8s.io/my-cluster unchanged
machine.cluster.k8s.io/worker unchanged
The Machine "my-control-plane" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"cluster.k8s.io/v1alpha1", "kind":"Machine", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"cluster.k8s.io/v1alpha1\",\"kind\":\"Machine\",\"metadata\":{\"annotations\":{},\"labels\":{\"cluster.k8s.io/cluster-name\":\"my-cluster\",\"set\":\"controlplane\"},\"name\":\"my-control-p …
```
> Fix to broken simple-cluster

- cloudinit/rumcmd.go
Inserts `--ignore-preflight-errors=all` into kubeadm commands
```release-note
NONE
```
> Insert --ignore-preflight-errors=all into kubeadm commands

- api/v1alpha2/dockercluster_types.go
- controllers/dockercluster_controller.go
- docker/loadbalancer.go
- docker/nodes.go
I think we should ensure a consistent approach across CAP* providers, so this PR...
BTW, with this implementation dockerCluster controller now manage properly the external resource/lb (use it if already exists, delete it using a finalizer)
```release-note
NONE
```
> Make cluster controller like CAPA awsCluster controller

- OWNERS_ALIASES
This PR adds @detiber as an admin of the project. I should not be the only one with admin access and @detiber already has it in cluster-api so he might as well also have it here.
```release-note
NONE
```
/assign @detiber
> Add detiber as project admin

- controllers/dockermachine_controller.go
Cleans up unnecessary requeues
```release-note
NONE
```
> Do not requeue while waiting for watched resources

- docker/actions/cluster_actions.go
- docker/actions/kind.go
**What this PR does / why we need it**: This PR allows the deletion of the final/first control plane
Fixes #109 
```release-note
NONE
```
> 🐛 Fix DockerMachine delete for first control plane

- api/v1alpha2/dockercluster_types.go
- api/v1alpha2/dockermachine_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
Similar to the recent work done in CAPA, CAPI and CABPK, this adds cluster-api categories to our cluster-api CRDs.
```release-note
NONE
```
> ✨ Add cluster-api category

- config/default/kustomization.yaml
- config/rbac/kustomization.yaml
- config/webhook/kustomization.yaml
@Arvinderpal reported an issue with kustomize v3.1. This fix makes CAPD work with the new kustomize using `kustomize edit fix` and then fixing the mistakes I believe that program makes.
```release-note
Supports kustomize v3.1.x
```
> Fixup YAML for kustomize v3.1.x

- cloudinit/kindadapter.go
- cloudinit/rumcmd.go
- cloudinit/runcmd_test.go
- cloudinit/unknown.go
- cloudinit/unknown_test.go
- cloudinit/writefiles.go
This is low priority, I did this on a recent plane ride and forgot to commit. It's a minor clean up of the cloud-init adapter code. It removes a lot of suffixes and cleans up some layers of indirection in favor of switch statements and simpler interfaces.
/cc @detiber 
```release-note
NONE
```
> cloudinit adapter clean up

- Dockerfile.dev
This PR renames the current `Dockerfile` into `Dockerfile.dev` and adds a production-ready  `Dockerfile`
The image size is 157MB, down from the ~2GB of the dev image
CAPD requires some dependencies installed in the docker image, so I'm using alpine as the base image instead of distroless, but I guess this is fine for the scope of CAPD
```release-note
NONE
```
/assign @chuckha @detiber @vincepri
> production ready dockerfile

- docker/nodes.go
Currently we attempt to create an additional controlplane immediately after creating the first controlplane, which results in an error reconciling the first machine and an orphaned docker container.
```release-note
NONE
```
> Fix controlplane init

- api/v1alpha2/dockermachine_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
- controllers/dockermachine_controller.go
- docker/machine.go
This enables the customization of the container image that is used for running a given DockerMachine instance. This is useful in situations where you'd like to customize the node image in some way to better suit your needs.
Fixes #
```release-note
```
> ✨ Add DockerMachine.Spec.CustomImage for customizing the container image the node runs

- config/crd/kustomization.yaml
This PR adds the DockerMachineTemplate type to the kustomize yaml manifest. This allows us to use DockerMachineTemplate types after applying the `kustomize build config` output to a cluster.
> 🏃 Adds dockermachinetemplates to the kustomization manifest

- controllers/dockermachine_controller.go
- controllers/dockermachine_controller_test.go
- go.mod
This PR Watches DockerClusters and requeues all DockerMachines when DockerCluster updates.
Fixes #223
> ✨ Watch dockercluster

- main.go
- sync-period flags can be passed as an argument
- If not provided, then value is defaulted to 10 minutes
Fixes # #228
> Made SyncPeriod configurable

- examples/simple-cluster.yaml
Currently there is still a v1alpha1 example in the current repo. To avoid confusing new users, and have a simple example to share, I updated the example to v1alpha2.
The structure of the example remains the same: deploy 1 cluster with 1 control plane node and 1 worker node.
I verified the example locally (on Mac), using the `gcr.io/kubernetes1-226021/manager:dev` image.
> 📖 Update simple-cluster example to v1alpha2

- config/manager/manager.yaml
For whatever reason trying to claim the file is a socket is a bad idea. Kubernetes doesn't think it's a socket but it works fine with this type removed.  In addition the docker lib is not necessary.
These changes have already happened in current release.
> 🐛 Clean up manager YAML
