- README.md
- examples/simple-cluster.yaml
Also changes the sample to use `controlplane` to match what the manager
is looking for.
> docs: update readme

- README.md
- actuators/machine.go
- cmd/capdctl/main.go
- cmd/kind-test/main.go
- kind/actions/cluster_actions.go
- kind/actions/kind.go
- kind/kubeadm/config.go
* Use machine name instead of generated name tied to kind
* Improve delete functionality to remove node from child cluster
* Set nodeRefs
> Several updates

- Dockerfile
/assign @chuckha 
/kind cleanup
/priority backlog
> Dockerfile: use the name of the project as working directory

- cmd/kind-test/main.go
kind-test did not compile due to API changes. 
Will need to get some automated tests building these binaries soon
> Fix the build

- SECURITY_CONTACTS
Closes #1 
@detiber 
@justinsb 
@luxas 
@timothysc 
I copied this from Cluster-API. Let me know if this is not ok. If not, timeout will be next Tuesday. Will ping again on Monday.
> Adds security contacts

- actuators/actuators.go
- actuators/machine.go
- cmd/capd-manager/main.go
- cmd/capdctl/main.go
- cmd/kind-test/main.go
- go.mod
- go.sum
- kind/actions/cluster_actions.go
- kind/actions/kind.go
fixes https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/15
> fix import paths

- README.md
- cmd/capdctl/main.go
Configures machine deployment YAML. 
Addresses: https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/29
> configure machine deployment

- cmd/capdctl/main.go
cc @amy 
fixes #33
Please see #32 if you are concerned about the copy pasta'd RBAC 😅
> Provide patch to events to the cluster-api system account

- actuators/machine.go
address #31 
Changes variable name `new` to `newMachine` and variable name `old` to `oldMachine`.
> change variable names

- actuators/actuators.go
> Temporary fix for cluster-api 1.4

- actuators/machine.go
> Fixup the provider id

- .gitignore
- cmd/capd-manager/main.go
Signed-off-by: Ashish Amarnath ashish.amarnath@gmail.com
> Fix provisioner name

- cmd/capdctl/main.go
> Fixup rbac for v0.1.4

- cmd/capdctl/main.go
Keep help messages in sync
Fixes #49 
```release-note
NONE
```
> Update capdctl subcommands help

- scripts/publish-manager.sh
Signed-off-by: Ashish Amarnath ashish.amarnath@gmail.com
> Build images with dev tag by default

- README.md
- scripts/publish-manager.sh
Makes `publish-manager.sh` usable when image registry is not in gcr
Fixes #
```release-note
NONE
```
> Update publish-manager to be more non gcp friendly

- Dockerfile
Post #27 building capd-manager images require `logger` dir to be added to the build container.
Without this `publish-manager.sh` fails.
Fixes #58
```release-note
NONE
```
> Add logger package to build container

- go.mod
- go.sum
These changes keep creeping into my other PRs.
So getting these changes in on their own.
Fixes #
```release-note
NONE
```
> update go mod files

- cmd/capdctl/main.go
It's spelled wrong and it bothers me
Fixes 
```release-note
NONE
```
> Typo in capdctl --help

- actuators/actuators.go
- cmd/capd-manager/main.go
- kind/actions/cluster_actions.go
I forgot to push this! 
/assign @vincepri
> Feedback from a recent PR I forgot to push

- .github/main.workflow
This PR starts addressing #67
This will build an image but will not push until it merges to master.
```release-note
NONE
```
/assign @detiber 
Sorry for all the spam >.< this one finally does what I want.
> Build container image on all pushes and publish image on push to master

- .github/main.workflow
This PR attempts to fix the broken name on the docker push.
```release-note
NONE
```
> Fix the name of the image in the github action

- .github/main.workflow
This is an attempt at trying out a new tagging strategy and seeing what happens  with releases.
```release-note
NONE
```
/assign @detiber
> a better tagging strategy

- hack/verify-all.sh
- hack/verify-docker-build.sh
To ensure an image for `capd-manager` can be built with the proposed changes in a PR
Fixes #60 
```release-note
NONE
```
> Add verify-docker-build to pre-submit tests

- hack/update-goimports.sh
- hack/verify-all.sh
- hack/verify-goimports.sh
**What this PR does / why we need it**:add a  goimports verivication
Fixes #78 
```release-note
```
> Add a goimports verification

- hack/verify-all.sh
Makes it easier to catch errors from the `verify-all.sh`
Fixes #
```release-note
NONE
```
> Log errors on verify failure

- hack/verify-all.sh
- hack/verify-gofmt.sh
This PR cleans up the verify scripts to make the output tell us what failed in a clean way.
```release-note
NONE
```
> Clean up verification tools

- .github/release.workflow
This should actually kick off a build now.
```release-note
NONE
```
> Fix release workflow

- .github/main.workflow
```release-note
NONE
```
/assign @ashish-amarnath
> Use a GITHUB_TOKEN secret

- .github/main.workflow
Need to configure docker to use gcloud login as auth credentials.
```release-note
NONE
```
> configure gcloud for docker

- .github/main.workflow
Actually resolve the right workflow action.
```release-note
NONE
```
> actually run push images

- .github/main.workflow
I swear the example didn't have quotes 😭 
```release-note
NONE
```
> quote the environment

- .github/main.workflow
This PR tries another attempt at getting the docker push to work.
```release-note
NONE
```
> fix up the workflow

- .github/main.workflow
This pr tries one last thing before I try replicating GitHub actions locally with act
```release-note
NONE
```
> add runs back in

- .goreleaser.yml
- Dockerfile
This will be v0.1.3
```release-note
NONE
```
> fixup goreleaser

- controllers/dockermachine_controller.go
This is a cleanup PR that uses cluster api's generic machine to infrastructure map func.
/assign @ncdc 
/cc @amy 
```release-note
NONE
```
> use cluster-api mapfunc

- controllers/dockermachine_controller.go
Fixes #146 
```release-note
```
> Use cluster api map function

- controllers/dockermachine_controller.go
This PR correctly matches apiversion with expected apiversion
Fixes #160
> Fix ownerref match

- cmd/manager/main.go
This PR registers the capi types with the manager
Fixes #158 
```release-note
```
> register capi types with  manager

- README.md
Fixes #132 
```release-note
NONE
```
> DOC: clarify what registry means

- OWNERS_ALIASES
Add myself as a maintainer for OWNERS
Fixes #
```release-note
NONE
```
> Add myself as a maintainer

- Dockerfile
- hack/verify-all.sh
To make `scripts/publish-manager.sh` run successfully
Fixes #
```release-note
NONE
```
/assign @chuckha
> Copy cloudinit packages to build manager binary

- controllers/dockermachine_controller.go
Refactor DockerMachineReconcile  to use CAPI util function
> Refactor DockerMachineReconcile  to use CAPI util function

- api/v1alpha2/dockermachine_types.go
- controllers/dockermachine_controller.go
Fixes #150 
```release-note
```
> reconcileDelete DockerMachine

- controllers/dockercluster_controller.go
- controllers/dockermachine_controller.go
- kind/actions/kind.go
Fixes #152 
```release-note
NONE
```
> Reconcile ELB in cluster controller

- cmd/manager/main.go
Fixes #
```release-note
NONE
```
> Call klog init

- cmd/manager/main.go
Fixes #
```release-note
NONE
```
> Fix logger name for machine controller

- .gitignore
- controllers/dockermachine_controller.go
Fixes #151 
```release-note
- Switch from Update() to Patch()
```
> chore: switch from Update() to Patch()

- README.md
Signed-off-by: Dan Finneran <dan@thebsdbox.co.uk>
This PR is just a simple typo fix for building the docker cluster-api provider
Fixes #
Ensures that building of the binaries is successful 
```release-note
NONE
```
> Fixes a tiny typo in the build instructions

- controllers/dockermachine_controller.go
- go.mod
Fixes #154 
```release-note
```
> Refactor the create function

- cloudinit/rumcmd.go
- cloudinit/runcmd_test.go
I had the PR ready, but @detiber was faster than me with https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/197, so feel free to close
The only difference here is that the hack is more explicit and some unit testing ...
```release-note
NONE
```
> hack kubeadm ignore errors

- api/v1alpha2/dockercluster_types.go
- api/v1alpha2/dockermachine_types.go
Adds storageversion to api types
```release-note
NONE
```
> Add storage version to api tyupes

- docker/actions/cluster_actions.go
We should check if `nodes.List` returns an error.
Fixes #
```release-note
```
> Check if nodes.List returned an error

- config/certmanager/kustomization.yaml
- config/crd/kustomization.yaml
- config/manager/kustomization.yaml
Fixes issues with running kustomize against `config/default`
```release-note
NONE
```
> Kustomize fixes

- Makefile
This makes it easier to figure out what commands are available via `make` without having to read through the `Makefile`. Implemented using the changes from kubernetes-sigs/cluster-api#631
```shell
$ make help
Usage:
make <target>
help             Display this help
test             Run tests
manager          Build manager binary
run              Run against the configured Kubernetes cluster in ~/.kube/config
install          Install CRDs into a cluster
deploy           Deploy controller in the configured Kubernetes cluster in ~/.kube/config
manifests        Generate manifests e.g. CRD, RBAC etc.
fmt              Run go fmt against code
vet              Run go vet against code
generate         Generate code
docker-build     Build the docker image …
```
> 🏃‍♂️ Add 'help' target to Makefile and make it the default

- .github/PULL_REQUEST_TEMPLATE.md
**What this PR does / why we need it**: This PR adds the new PR template.
> ✨ Update PR template

- README.md
This PR Updates the README to be accurate to current master.
Fixes #230
> 📖 Update the README

- config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
**What this PR does / why we need it**: This PR adds a generated file I forgot to add earlier
> :sparkles: Commit machinetemplate CRD

- main.go
Trying to keep consistency in how the imports are named across the repository.
Fixes #
> 🏃‍♂️ Name v1alpha2 imports

- .github/ISSUE_TEMPLATE/bug_report.md
Cleaning up github issue template
Fixes #
> 🐛 Remove capdctl version from issue template

- docker/machine.go
> ✨ Notify when failing back to default container image

- README.md
**What this PR does / why we need it**: This PR informs users the code is no longer under development and has MOVED to cluster api
Fixes #
/assign @ncdc
> 📖 Inform users of code move
